export const APP_THEME = 'APP_THEME';

export const USER_SIGNUP_START = 'USER_SIGNUP_START';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_IN_USER_ERROR = 'LOG_IN_USER_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_SINGLE_ARTICLE_START = 'GET_SINGLE_ARTICLE_START';
export const GET_SINGLE_ARTICLE_SUCCESS = 'GET_SINGLE_ARTICLE_SUCCESS';
export const GET_SINGLE_ARTICLE_FAIL = 'GET_SINGLE_ARTICLE_FAIL';

export const CREATE_COMMENT_ON_ARTICLE_START =
  'CREATE_COMMENT_ON_ARTICLE_START';
export const CREATE_COMMENT_ON_ARTICLE_SUCCESS =
  'CREATE_COMMENT_ON_ARTICLE_SUCCESS';
export const ADD_ALL_ARTICLES = 'ADD_ALL_ARTICLES';
export const UPDATE_ARTICLES_LOADING = 'UPDATE_ARTICLES_LOADING';
export const ADD_ALL_TAGS = 'ADD_ALL_TAGS';
export const FETCH_ALL_ARTICLES = 'FETCH_ALL_ARTICLES';
export const FETCH_ALL_ARTICLES_START = 'FETCH_ALL_ARTICLES_START';
export const FETCH_MORE_ARTICLES = 'FETCH_MORE_ARTICLES';
export const UPDATE_EMPTY_NARROWED = 'UPDATE_EMPTY_NARROWED';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_START = 'CREATE_ARTICLE_START';
export const CREATE_BOOKMARK_SUCCESS = 'CREATE_BOOKMARK_SUCCESS';
export const CREATE_BOOKMARK_FAIL = 'CREATE_BOOKMARK_FAIL';
export const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS';
export const DELETE_BOOKMARK_FAIL = 'DELETE_BOOKMARK_FAIL';
export const GET_ALL_BOOKMARKS_SUCCESS = 'GET_ALL_BOOKMARKS_SUCCESS';
export const GET_ALL_BOOKMARKS_FAIL = 'GET_ALL_BOOKMARKS_FAIL';
export const GET_PUBLISHED_ARTICLES_START = 'GET_PUBLISHED_ARTICLES_START';
export const GET_PUBLISHED_ARTICLES_SUCCESS = 'GET_PUBLISHED_ARTICLES_SUCCESS';
export const GET_DRAFT_ARTICLES_START = 'GET_DRAFT_ARTICLES_START';
export const GET_DRAFT_ARTICLES_SUCCESS = 'GET_DRAFT_ARTICLES_SUCCESS';
export const UNPUBLISHED_ARTICLES_SUCCESS = 'UNPUBLISHED_ARTICLES_SUCCESS';
export const SINGLE_ARTILCE_SLUG = 'SINGLE_ARTILCE_SLUG';
export const ERROR_RESPONSE_ON_ARTICLE = 'ERROR_RESPONSE_ON_ARTICLE';
export const PUBLISHED_ARTICLES_SUCCESS = 'PUBLISHED_ARTICLES_SUCCESS';


