export const APP_THEME = 'APP_THEME';

export const USER_SIGNUP_START = 'USER_SIGNUP_START';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_IN_USER_ERROR = 'LOG_IN_USER_ERROR';

export const GET_SINGLE_ARTICLE_START = 'GET_SINGLE_ARTICLE_START';
export const GET_SINGLE_ARTICLE_SUCCESS = 'GET_SINGLE_ARTICLE_SUCCESS';
export const GET_SINGLE_ARTICLE_FAIL = 'GET_SINGLE_ARTICLE_FAIL';
